### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Unloaded123456** [arek-kwapis/rustedanvil#6]
When I run downloadmcassets.py, " ModuleNotFoundError: No module named 'requests' " error appears. I use Python 3.11.2.

**Comment by arek-kwapis** [comment]
Yes, it is because requests is not part of the standard python package and must be manually downloaded with pip

`pip install requests`

Since this is just a developmental utility and not meant to be used until Milestone 2 when it will be used and refactored properly, I see no current need to rework it currently.
